input.onButtonPressed(Button.A, function () {
    microIoT.microIoT_clear()
    microIoT.microIoT_showUserText(0, "Move Servo S1 to 0")
    microIoT.microIoT_ServoRun(microIoT.aServos.S1, 0)
    basic.pause(1000)
    microIoT.microIoT_clear()
    microIoT.microIoT_showUserText(0, "Move Servo S1 to 180")
    microIoT.microIoT_ServoRun(microIoT.aServos.S1, 180)
    basic.pause(1000)
    microIoT.microIoT_clear()
    microIoT.microIoT_showUserText(0, "Move Servo S1 to 90")
    microIoT.microIoT_ServoRun(microIoT.aServos.S1, 180)
    basic.pause(1000)
    microIoT.microIoT_clear()
    microIoT.microIoT_showUserText(0, "Move Servo S1 Back to 0")
    microIoT.microIoT_ServoRun(microIoT.aServos.S1, 0)
    basic.pause(1000)
})
basic.showIcon(IconNames.Heart)
basic.pause(500)
microIoT.microIoT_initDisplay()
microIoT.microIoT_clear()
microIoT.microIoT_showUserText(0, "Hello Frank")
basic.pause(1000)
microIoT.microIoT_showUserText(1, "Press Button A to test Servo")
